export const SET_FILMS_LIST_ADMIN = "SET_FILMS_LIST_ADMIN";
export const SET_FILMS_TYPE_MOVIES = "SET_FILMS_TYPE_MOVIES";
export const SET_FILMS_TYPE_TV = "SET_FILMS_TYPE_TV";
export const SET_FILMS_TRENDING = "SET_FILMS_TRENDING";
export const SET_FILMS_LASTEST_MOVIES = "SET_FILMS_LASTEST_MOVIES";
export const SET_FILMS_LASTEST_TV = "SET_FILMS_LASTEST_TV";
export const SET_FILMS_FILTER = "SET_FILMS_FILTER";

export const SET_FILM_ADMIN = "SET_FILM_ADMIN";
export const SET_FILM = "SET_FILM";
export const SET_FILM_SUGGESTS = "SET_FILM_SUGGESTS";
export const SET_SEARCH_VALUE_INPUT = "SET_SEARCH_VALUE_INPUT";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_SEARCH_RESULTS_FULL = "SET_SEARCH_RESULTS_FULL";

export const SET_ID_FILM_DELETE = "SET_ID_FILM_DELETE";
export const SET_FILM_SORT_DEL = "SET_FILM_SORT_DEL";
