export const SET_FILMS_LIST_ADMIN = "SET_FILMS_LIST_ADMIN";
export const SET_FILMS_TYPE_MOVIES = "SET_FILMS_TYPE_MOVIES";
export const SET_FILMS_TYPE_TV = "SET_FILMS_TYPE_TV";
export const SET_FILMS_TRENDING = "SET_FILMS_TRENDING";
export const SET_FILMS_LASTEST_MOVIES = "SET_FILMS_LASTEST_MOVIES";
export const SET_FILMS_LASTEST_TV = "SET_FILMS_LASTEST_TV";
export const SET_FILMS_FILTER = "SET_FILMS_FILTER";

export const SET_FILM_ADMIN = "SET_FILM_ADMIN";
export const SET_FILM = "SET_FILM";
export const SET_FILM_SUGGESTS = "SET_FILM_SUGGESTS";
export const SET_SEARCH_VALUE_INPUT = "SET_SEARCH_VALUE_INPUT";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_SEARCH_RESULTS_FULL = "SET_SEARCH_RESULTS_FULL";

export const SET_ID_FILM_DELETE = "SET_ID_FILM_DELETE";
export const SET_FILM_SORT_DEL = "SET_FILM_SORT_DEL";

export const SET_FILM_TRASH = "SET_FILM_TRASH";
export const SET_ID_FILM_RESTORE = "SET_ID_FILM_RESTORE";
export const SET_FILM_RESTORE = "SET_FILM_RESTORE";
export const SET_ID_FILM_REMOVE = "SET_ID_FILM_REMOVE";
export const SET_FILM_REMOVED = "SET_FILM_REMOVED";
export const SET_FILMS_WATCH_LIST = "SET_FILMS_WATCH_LIST";
// Auth const

export const SET_USER_INFOR = "SET_USER_INFOR";
export const SET_USER_ALL_INFO = "SET_USER_ALL_INFO";
export const SET_UPDATE_INFOR_USER = "SET_UPDATE_INFOR_USER";
// Controll
export const SET_MODAL_SHOW = "SET_MODAL_SHOW";
// Admin
export const SET_ALL_USERS = "SET_ALL_USERS";
export const SET_USER_RULE = "SET_USER_RULE";
// Auth
export const SET_AUTH_LOGIN = "SET_AUTH_LOGIN";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
